version: "3.4"
services:
  # redis_pubsub:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: allocation-image
  #   depends_on:
  #     - postgres
  #     - redis
  #   volumes:
  #     - ./src:/src
  #     - ./tests:/tests
  #   entrypoint:
  #     - python
  #     - /src/app/entrypoints/redis_event_consumer.py

  # user-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - GITHUB_TOKEN=${GITHUB_TOKEN}
  #   image: user-service
  #   depends_on:
  #     - db
  #   # volumes:
  #   #   - ./src:/user-service/src
  #   #   - ./tests:/user-service/tests
  #   command: poetry run uvicorn src.entrypoints.app:app --host 0.0.0.0 --port 8000
  #   # command:
  #   #   [
  #   #     "sh",
  #   #     "-c",
  #   #     "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m poetry run uvicorn src.entrypoints.app:app --host 0.0.0.0 --port 8000",
  #   #   ]
  #   ports:
  #     - "8000:8000"
  #     - "5678:5678"

  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpw
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:
